# Generated by Django 4.2.1 on 2023-05-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
